// Curated exercise library, sorted by name. Originally derived from
// free-exercise-db (https://github.com/yuhonas/free-exercise-db), then
// condensed: grip/angle variants folded into their base movement, and equipment
// names stripped from exercise names (equipment lives in the `equipment` field
// instead), merging any entries that collided as a result.
//
// Naming rule for the collisions that could NOT be merged: where two entries are
// the same base movement performed with a different implement, they are genuinely
// different Template Exercises (ADR 0003), so BOTH carry their equipment as a
// name prefix — "Barbell Deadlift" / "Cable Deadlift", not "Deadlift" /
// "Deadlifts". The nine pluralised names that previously dodged those collisions
// are gone; a plural name here is now always a real plural, never a disambiguator.
import type { SeedExercise } from "./types.js";

export const SEED_EXERCISES: SeedExercise[] = [
  {
    name: "Ab Crunch",
    bodyPosition: "seated",
    laterality: "bilateral",
    movementPattern: "core",
    equipment: "machine",
    muscles: [{ muscleGroup: "core", role: "primary" }],
  },
  {
    name: "Ab Roller",
    bodyPosition: "kneeling",
    laterality: "bilateral",
    movementPattern: "core",
    muscles: [
      { muscleGroup: "core", role: "primary" },
      { muscleGroup: "delts", role: "secondary" },
    ],
  },
  {
    name: "Ab Rollout",
    bodyPosition: "kneeling",
    laterality: "bilateral",
    movementPattern: "core",
    equipment: "barbell",
    muscles: [
      { muscleGroup: "core", role: "primary" },
      { muscleGroup: "back", role: "secondary" },
      { muscleGroup: "delts", role: "secondary" },
    ],
  },
  {
    name: "Arnold Press",
    bodyPosition: "seated",
    laterality: "bilateral",
    movementPattern: "push",
    equipment: "kettlebell",
    muscles: [
      { muscleGroup: "delts", role: "primary" },
      { muscleGroup: "triceps", role: "secondary" },
    ],
  },
  {
    name: "Band Hip Adduction",
    bodyPosition: "seated",
    laterality: "bilateral",
    movementPattern: "pull",
    equipment: "band",
    muscles: [{ muscleGroup: "glutes", role: "primary" }],
  },
  {
    name: "Band Skull Crusher",
    bodyPosition: "lying",
    laterality: "bilateral",
    movementPattern: "push",
    equipment: "band",
    muscles: [{ muscleGroup: "triceps", role: "primary" }],
  },
  {
    name: "Barbell Deadlift",
    bodyPosition: "standing",
    laterality: "bilateral",
    movementPattern: "hinge",
    equipment: "barbell",
    muscles: [
      { muscleGroup: "back", role: "primary" },
      { muscleGroup: "quads", role: "primary" },
      { muscleGroup: "calves", role: "secondary" },
      { muscleGroup: "forearms", role: "secondary" },
      { muscleGroup: "glutes", role: "secondary" },
      { muscleGroup: "hamstrings", role: "secondary" },
      { muscleGroup: "traps", role: "secondary" },
    ],
  },
  {
    name: "Barbell Lunge",
    bodyPosition: "standing",
    laterality: "alternating",
    movementPattern: "lunge",
    equipment: "barbell",
    muscles: [
      { muscleGroup: "quads", role: "primary" },
      { muscleGroup: "calves", role: "secondary" },
      { muscleGroup: "glutes", role: "secondary" },
      { muscleGroup: "hamstrings", role: "secondary" },
    ],
  },
  {
    name: "Barbell Preacher Curl",
    bodyPosition: "seated",
    laterality: "bilateral",
    movementPattern: "pull",
    equipment: "barbell",
    muscles: [
      { muscleGroup: "biceps", role: "primary" },
      { muscleGroup: "forearms", role: "secondary" },
    ],
  },
  {
    name: "Barbell Seated Palms-Up Wrist Curl",
    bodyPosition: "seated",
    laterality: "bilateral",
    gripOrientation: "supinated",
    movementPattern: "pull",
    equipment: "barbell",
    muscles: [{ muscleGroup: "forearms", role: "primary" }],
  },
  {
    name: "Barbell Shrug",
    bodyPosition: "standing",
    laterality: "bilateral",
    movementPattern: "pull",
    equipment: "barbell",
    muscles: [
      { muscleGroup: "traps", role: "primary" },
      { muscleGroup: "forearms", role: "secondary" },
    ],
  },
  {
    name: "Bench Dips",
    bodyPosition: "hanging",
    laterality: "bilateral",
    movementPattern: "push",
    equipment: "bodyweight",
    muscles: [
      { muscleGroup: "triceps", role: "primary" },
      { muscleGroup: "chest", role: "secondary" },
      { muscleGroup: "delts", role: "secondary" },
    ],
  },
  {
    name: "Bench Press",
    bodyPosition: "lying",
    laterality: "bilateral",
    movementPattern: "push",
    equipment: "barbell",
    muscles: [
      { muscleGroup: "chest", role: "primary" },
      { muscleGroup: "delts", role: "secondary" },
      { muscleGroup: "triceps", role: "secondary" },
    ],
  },
  {
    name: "Bent Over Row",
    bodyPosition: "bent-over",
    laterality: "bilateral",
    movementPattern: "pull",
    equipment: "barbell",
    muscles: [
      { muscleGroup: "back", role: "primary" },
      { muscleGroup: "biceps", role: "secondary" },
      { muscleGroup: "delts", role: "secondary" },
    ],
  },
  {
    name: "Bent-Arm Pullover",
    bodyPosition: "lying",
    laterality: "bilateral",
    movementPattern: "pull",
    equipment: "barbell",
    muscles: [
      { muscleGroup: "back", role: "primary" },
      { muscleGroup: "chest", role: "primary" },
      { muscleGroup: "delts", role: "secondary" },
      { muscleGroup: "triceps", role: "secondary" },
    ],
  },
  {
    name: "Bicep Curl",
    bodyPosition: "standing",
    laterality: "bilateral",
    movementPattern: "pull",
    equipment: "dumbbell",
    muscles: [
      { muscleGroup: "biceps", role: "primary" },
      { muscleGroup: "forearms", role: "secondary" },
    ],
  },
  {
    name: "Body Tricep Press",
    bodyPosition: "lying",
    laterality: "bilateral",
    movementPattern: "push",
    equipment: "bodyweight",
    muscles: [{ muscleGroup: "triceps", role: "primary" }],
  },
  {
    name: "Bodyweight Russian Twist",
    bodyPosition: "seated",
    laterality: "bilateral",
    movementPattern: "core",
    equipment: "bodyweight",
    muscles: [
      { muscleGroup: "core", role: "primary" },
      { muscleGroup: "back", role: "secondary" },
    ],
  },
  {
    name: "Butt Lift (Bridge)",
    bodyPosition: "lying",
    laterality: "bilateral",
    movementPattern: "push",
    equipment: "bodyweight",
    muscles: [
      { muscleGroup: "glutes", role: "primary" },
      { muscleGroup: "hamstrings", role: "secondary" },
    ],
  },
  {
    name: "Butterfly",
    bodyPosition: "seated",
    laterality: "bilateral",
    movementPattern: "pull",
    equipment: "machine",
    muscles: [{ muscleGroup: "chest", role: "primary" }],
  },
  {
    name: "Cable Deadlift",
    bodyPosition: "standing",
    laterality: "bilateral",
    movementPattern: "hinge",
    equipment: "cable",
    muscles: [
      { muscleGroup: "quads", role: "primary" },
      { muscleGroup: "back", role: "secondary" },
      { muscleGroup: "forearms", role: "secondary" },
      { muscleGroup: "glutes", role: "secondary" },
      { muscleGroup: "hamstrings", role: "secondary" },
    ],
  },
  {
    name: "Cable Hip Adduction",
    bodyPosition: "seated",
    laterality: "bilateral",
    movementPattern: "pull",
    equipment: "cable",
    muscles: [{ muscleGroup: "quads", role: "primary" }],
  },
  {
    name: "Cable Lying Triceps Extension",
    bodyPosition: "lying",
    laterality: "bilateral",
    movementPattern: "push",
    equipment: "cable",
    muscles: [{ muscleGroup: "triceps", role: "primary" }],
  },
  {
    name: "Cable Russian Twist",
    bodyPosition: "seated",
    laterality: "bilateral",
    movementPattern: "core",
    equipment: "cable",
    muscles: [{ muscleGroup: "core", role: "primary" }],
  },
  {
    name: "Cable Shrug",
    bodyPosition: "standing",
    laterality: "bilateral",
    movementPattern: "pull",
    equipment: "cable",
    muscles: [{ muscleGroup: "traps", role: "primary" }],
  },
  {
    name: "Calf Press",
    bodyPosition: "seated",
    laterality: "bilateral",
    movementPattern: "push",
    equipment: "machine",
    muscles: [{ muscleGroup: "calves", role: "primary" }],
  },
  {
    name: "Chest Pass",
    bodyPosition: "standing",
    laterality: "bilateral",
    movementPattern: "push",
    equipment: "medicine-ball",
    muscles: [
      { muscleGroup: "chest", role: "primary" },
      { muscleGroup: "delts", role: "secondary" },
      { muscleGroup: "triceps", role: "secondary" },
    ],
  },
  {
    name: "Chest Press",
    bodyPosition: "seated",
    laterality: "bilateral",
    movementPattern: "push",
    equipment: "cable",
    muscles: [
      { muscleGroup: "chest", role: "primary" },
      { muscleGroup: "delts", role: "secondary" },
      { muscleGroup: "triceps", role: "secondary" },
    ],
  },
  {
    name: "Clean",
    bodyPosition: "standing",
    laterality: "bilateral",
    movementPattern: "pull",
    equipment: "barbell",
    muscles: [
      { muscleGroup: "hamstrings", role: "primary" },
      { muscleGroup: "back", role: "secondary" },
      { muscleGroup: "calves", role: "secondary" },
      { muscleGroup: "delts", role: "secondary" },
      { muscleGroup: "forearms", role: "secondary" },
      { muscleGroup: "glutes", role: "secondary" },
      { muscleGroup: "quads", role: "secondary" },
      { muscleGroup: "traps", role: "secondary" },
    ],
  },
  {
    name: "Concentration Curls",
    bodyPosition: "seated",
    laterality: "unilateral",
    movementPattern: "pull",
    equipment: "dumbbell",
    muscles: [
      { muscleGroup: "biceps", role: "primary" },
      { muscleGroup: "forearms", role: "secondary" },
    ],
  },
  {
    name: "Crossover",
    bodyPosition: "standing",
    laterality: "bilateral",
    movementPattern: "push",
    equipment: "cable",
    muscles: [
      { muscleGroup: "chest", role: "primary" },
      { muscleGroup: "delts", role: "secondary" },
    ],
  },
  {
    name: "Crunch",
    bodyPosition: "lying",
    laterality: "bilateral",
    movementPattern: "core",
    equipment: "cable",
    muscles: [{ muscleGroup: "core", role: "primary" }],
  },
  {
    name: "Curl",
    bodyPosition: "standing",
    laterality: "bilateral",
    movementPattern: "pull",
    equipment: "barbell",
    muscles: [
      { muscleGroup: "biceps", role: "primary" },
      { muscleGroup: "forearms", role: "secondary" },
    ],
  },
  {
    name: "Dead Bug",
    bodyPosition: "lying",
    laterality: "alternating",
    movementPattern: "core",
    equipment: "bodyweight",
    muscles: [{ muscleGroup: "core", role: "primary" }],
  },
  {
    name: "Dead Clean",
    bodyPosition: "standing",
    laterality: "bilateral",
    movementPattern: "pull",
    equipment: "kettlebell",
    muscles: [
      { muscleGroup: "hamstrings", role: "primary" },
      { muscleGroup: "back", role: "secondary" },
      { muscleGroup: "calves", role: "secondary" },
      { muscleGroup: "glutes", role: "secondary" },
      { muscleGroup: "quads", role: "secondary" },
      { muscleGroup: "traps", role: "secondary" },
    ],
  },
  {
    name: "Decline Crunch",
    bodyPosition: "decline",
    laterality: "bilateral",
    movementPattern: "core",
    equipment: "bodyweight",
    muscles: [{ muscleGroup: "core", role: "primary" }],
  },
  {
    name: "Dip",
    bodyPosition: "hanging",
    laterality: "bilateral",
    movementPattern: "push",
    equipment: "machine",
    muscles: [
      { muscleGroup: "triceps", role: "primary" },
      { muscleGroup: "chest", role: "secondary" },
      { muscleGroup: "delts", role: "secondary" },
    ],
  },
  {
    name: "Donkey Calf Raises",
    bodyPosition: "bent-over",
    laterality: "bilateral",
    movementPattern: "push",
    muscles: [{ muscleGroup: "calves", role: "primary" }],
  },
  {
    name: "Double Jerk",
    bodyPosition: "standing",
    laterality: "bilateral",
    movementPattern: "push",
    equipment: "kettlebell",
    muscles: [
      { muscleGroup: "delts", role: "primary" },
      { muscleGroup: "calves", role: "secondary" },
      { muscleGroup: "quads", role: "secondary" },
      { muscleGroup: "triceps", role: "secondary" },
    ],
  },
  {
    name: "Double Snatch",
    bodyPosition: "standing",
    laterality: "bilateral",
    movementPattern: "pull",
    equipment: "kettlebell",
    muscles: [
      { muscleGroup: "delts", role: "primary" },
      { muscleGroup: "glutes", role: "secondary" },
      { muscleGroup: "hamstrings", role: "secondary" },
      { muscleGroup: "quads", role: "secondary" },
    ],
  },
  {
    name: "Dumbbell Lunge",
    bodyPosition: "standing",
    laterality: "alternating",
    movementPattern: "lunge",
    equipment: "dumbbell",
    muscles: [
      { muscleGroup: "quads", role: "primary" },
      { muscleGroup: "calves", role: "secondary" },
      { muscleGroup: "glutes", role: "secondary" },
      { muscleGroup: "hamstrings", role: "secondary" },
    ],
  },
  {
    name: "Dumbbell Lying Triceps Extension",
    bodyPosition: "lying",
    laterality: "bilateral",
    movementPattern: "push",
    equipment: "dumbbell",
    muscles: [
      { muscleGroup: "triceps", role: "primary" },
      { muscleGroup: "chest", role: "secondary" },
      { muscleGroup: "delts", role: "secondary" },
    ],
  },
  {
    name: "Dumbbell Seated Palms-Up Wrist Curl",
    bodyPosition: "seated",
    laterality: "bilateral",
    gripOrientation: "supinated",
    movementPattern: "pull",
    equipment: "dumbbell",
    muscles: [{ muscleGroup: "forearms", role: "primary" }],
  },
  {
    name: "EZ-Bar Skull Crusher",
    bodyPosition: "lying",
    laterality: "bilateral",
    movementPattern: "push",
    equipment: "ez-bar",
    muscles: [
      { muscleGroup: "triceps", role: "primary" },
      { muscleGroup: "forearms", role: "secondary" },
    ],
  },
  {
    name: "Face Pull",
    bodyPosition: "standing",
    laterality: "bilateral",
    movementPattern: "pull",
    equipment: "cable",
    muscles: [
      { muscleGroup: "delts", role: "primary" },
      { muscleGroup: "back", role: "secondary" },
    ],
  },
  {
    name: "Farmer's Walk",
    bodyPosition: "standing",
    laterality: "bilateral",
    movementPattern: "carry",
    muscles: [
      { muscleGroup: "forearms", role: "primary" },
      { muscleGroup: "back", role: "secondary" },
      { muscleGroup: "core", role: "secondary" },
      { muscleGroup: "glutes", role: "secondary" },
      { muscleGroup: "hamstrings", role: "secondary" },
      { muscleGroup: "quads", role: "secondary" },
      { muscleGroup: "traps", role: "secondary" },
    ],
  },
  {
    name: "Flyes",
    bodyPosition: "lying",
    laterality: "bilateral",
    movementPattern: "push",
    equipment: "dumbbell",
    muscles: [
      { muscleGroup: "chest", role: "primary" },
      { muscleGroup: "core", role: "secondary" },
      { muscleGroup: "delts", role: "secondary" },
      { muscleGroup: "triceps", role: "secondary" },
    ],
  },
  {
    name: "Front Raise",
    bodyPosition: "standing",
    laterality: "bilateral",
    movementPattern: "push",
    equipment: "dumbbell",
    muscles: [{ muscleGroup: "delts", role: "primary" }],
  },
  {
    name: "Front Raise And Pullover",
    bodyPosition: "lying",
    laterality: "bilateral",
    movementPattern: "pull",
    equipment: "barbell",
    muscles: [
      { muscleGroup: "chest", role: "primary" },
      { muscleGroup: "back", role: "secondary" },
      { muscleGroup: "delts", role: "secondary" },
      { muscleGroup: "triceps", role: "secondary" },
    ],
  },
  {
    name: "Full Twist",
    bodyPosition: "standing",
    laterality: "bilateral",
    movementPattern: "core",
    equipment: "medicine-ball",
    muscles: [
      { muscleGroup: "core", role: "primary" },
      { muscleGroup: "delts", role: "secondary" },
    ],
  },
  {
    name: "Glute Ham Raise",
    bodyPosition: "kneeling",
    laterality: "bilateral",
    movementPattern: "pull",
    equipment: "machine",
    muscles: [
      { muscleGroup: "hamstrings", role: "primary" },
      { muscleGroup: "calves", role: "secondary" },
      { muscleGroup: "glutes", role: "secondary" },
    ],
  },
  {
    name: "Glute Kickback",
    bodyPosition: "kneeling",
    laterality: "unilateral",
    movementPattern: "push",
    equipment: "bodyweight",
    muscles: [
      { muscleGroup: "glutes", role: "primary" },
      { muscleGroup: "hamstrings", role: "secondary" },
    ],
  },
  {
    name: "Goblet Squat",
    bodyPosition: "standing",
    laterality: "bilateral",
    movementPattern: "squat",
    equipment: "kettlebell",
    muscles: [
      { muscleGroup: "quads", role: "primary" },
      { muscleGroup: "calves", role: "secondary" },
      { muscleGroup: "delts", role: "secondary" },
      { muscleGroup: "glutes", role: "secondary" },
      { muscleGroup: "hamstrings", role: "secondary" },
    ],
  },
  {
    name: "Good Morning",
    bodyPosition: "standing",
    laterality: "bilateral",
    movementPattern: "hinge",
    equipment: "barbell",
    muscles: [
      { muscleGroup: "hamstrings", role: "primary" },
      { muscleGroup: "back", role: "secondary" },
      { muscleGroup: "core", role: "secondary" },
      { muscleGroup: "glutes", role: "secondary" },
    ],
  },
  {
    name: "Hack Squat",
    bodyPosition: "standing",
    laterality: "bilateral",
    movementPattern: "squat",
    equipment: "barbell",
    muscles: [
      { muscleGroup: "quads", role: "primary" },
      { muscleGroup: "calves", role: "secondary" },
      { muscleGroup: "forearms", role: "secondary" },
      { muscleGroup: "glutes", role: "secondary" },
      { muscleGroup: "hamstrings", role: "secondary" },
    ],
  },
  {
    name: "Hammer Curls",
    bodyPosition: "standing",
    laterality: "bilateral",
    gripOrientation: "neutral",
    movementPattern: "pull",
    equipment: "dumbbell",
    muscles: [{ muscleGroup: "biceps", role: "primary" }],
  },
  {
    name: "Hammer Curls - Rope Attachment",
    bodyPosition: "standing",
    laterality: "bilateral",
    gripOrientation: "neutral",
    movementPattern: "pull",
    equipment: "cable",
    muscles: [{ muscleGroup: "biceps", role: "primary" }],
  },
  {
    name: "Hang Clean",
    bodyPosition: "standing",
    laterality: "bilateral",
    movementPattern: "pull",
    equipment: "barbell",
    muscles: [
      { muscleGroup: "hamstrings", role: "primary" },
      { muscleGroup: "quads", role: "primary" },
      { muscleGroup: "back", role: "secondary" },
      { muscleGroup: "calves", role: "secondary" },
      { muscleGroup: "delts", role: "secondary" },
      { muscleGroup: "forearms", role: "secondary" },
      { muscleGroup: "glutes", role: "secondary" },
      { muscleGroup: "traps", role: "secondary" },
    ],
  },
  {
    name: "Hang Power Clean",
    bodyPosition: "standing",
    laterality: "bilateral",
    movementPattern: "pull",
    equipment: "machine",
    muscles: [
      { muscleGroup: "hamstrings", role: "primary" },
      { muscleGroup: "back", role: "secondary" },
      { muscleGroup: "delts", role: "secondary" },
      { muscleGroup: "glutes", role: "secondary" },
      { muscleGroup: "quads", role: "secondary" },
      { muscleGroup: "traps", role: "secondary" },
    ],
  },
  {
    name: "Hang Snatch",
    bodyPosition: "standing",
    laterality: "bilateral",
    movementPattern: "pull",
    equipment: "barbell",
    muscles: [
      { muscleGroup: "hamstrings", role: "primary" },
      { muscleGroup: "back", role: "secondary" },
      { muscleGroup: "calves", role: "secondary" },
      { muscleGroup: "core", role: "secondary" },
      { muscleGroup: "delts", role: "secondary" },
      { muscleGroup: "forearms", role: "secondary" },
      { muscleGroup: "glutes", role: "secondary" },
      { muscleGroup: "quads", role: "secondary" },
      { muscleGroup: "traps", role: "secondary" },
    ],
  },
  {
    name: "Hanging Leg Raise",
    bodyPosition: "hanging",
    laterality: "bilateral",
    movementPattern: "core",
    equipment: "bodyweight",
    muscles: [{ muscleGroup: "core", role: "primary" }],
  },
  {
    name: "Hanging Pike",
    bodyPosition: "hanging",
    laterality: "bilateral",
    movementPattern: "core",
    equipment: "bodyweight",
    muscles: [{ muscleGroup: "core", role: "primary" }],
  },
  {
    name: "High Curls",
    bodyPosition: "standing",
    laterality: "bilateral",
    movementPattern: "pull",
    equipment: "cable",
    muscles: [{ muscleGroup: "biceps", role: "primary" }],
  },
  {
    name: "Hip Thrust",
    bodyPosition: "lying",
    laterality: "bilateral",
    movementPattern: "hinge",
    equipment: "barbell",
    muscles: [
      { muscleGroup: "glutes", role: "primary" },
      { muscleGroup: "calves", role: "secondary" },
      { muscleGroup: "hamstrings", role: "secondary" },
    ],
  },
  {
    name: "Hyperextensions (Back Extensions)",
    bodyPosition: "bent-over",
    laterality: "bilateral",
    movementPattern: "hinge",
    muscles: [
      { muscleGroup: "back", role: "primary" },
      { muscleGroup: "glutes", role: "secondary" },
      { muscleGroup: "hamstrings", role: "secondary" },
    ],
  },
  {
    name: "Incline Row",
    bodyPosition: "incline",
    laterality: "bilateral",
    movementPattern: "pull",
    equipment: "dumbbell",
    muscles: [
      { muscleGroup: "back", role: "primary" },
      { muscleGroup: "biceps", role: "secondary" },
      { muscleGroup: "delts", role: "secondary" },
      { muscleGroup: "forearms", role: "secondary" },
    ],
  },
  {
    name: "Inverted Row",
    bodyPosition: "lying",
    laterality: "bilateral",
    movementPattern: "pull",
    equipment: "bodyweight",
    muscles: [{ muscleGroup: "back", role: "primary" }],
  },
  {
    name: "Iso Row",
    bodyPosition: "seated",
    laterality: "bilateral",
    movementPattern: "pull",
    equipment: "machine",
    muscles: [
      { muscleGroup: "back", role: "primary" },
      { muscleGroup: "biceps", role: "secondary" },
    ],
  },
  {
    name: "Lat Pulldown",
    bodyPosition: "seated",
    laterality: "bilateral",
    movementPattern: "pull",
    equipment: "cable",
    muscles: [
      { muscleGroup: "back", role: "primary" },
      { muscleGroup: "biceps", role: "secondary" },
      { muscleGroup: "delts", role: "secondary" },
    ],
  },
  {
    name: "Leg Curl",
    bodyPosition: "lying",
    laterality: "bilateral",
    movementPattern: "pull",
    equipment: "exercise-ball",
    muscles: [
      { muscleGroup: "hamstrings", role: "primary" },
      { muscleGroup: "calves", role: "secondary" },
      { muscleGroup: "glutes", role: "secondary" },
    ],
  },
  {
    name: "Leg Extensions",
    bodyPosition: "seated",
    laterality: "bilateral",
    movementPattern: "push",
    equipment: "machine",
    muscles: [{ muscleGroup: "quads", role: "primary" }],
  },
  {
    name: "Leg Lift",
    bodyPosition: "lying",
    laterality: "bilateral",
    movementPattern: "push",
    equipment: "bodyweight",
    muscles: [
      { muscleGroup: "glutes", role: "primary" },
      { muscleGroup: "hamstrings", role: "secondary" },
    ],
  },
  {
    name: "Leg Press",
    bodyPosition: "seated",
    laterality: "bilateral",
    movementPattern: "push",
    equipment: "machine",
    muscles: [
      { muscleGroup: "quads", role: "primary" },
      { muscleGroup: "calves", role: "secondary" },
      { muscleGroup: "glutes", role: "secondary" },
      { muscleGroup: "hamstrings", role: "secondary" },
    ],
  },
  {
    name: "Leg-Over Floor Press",
    bodyPosition: "lying",
    laterality: "bilateral",
    rangeOfMotion: "partial",
    movementPattern: "push",
    equipment: "kettlebell",
    muscles: [
      { muscleGroup: "chest", role: "primary" },
      { muscleGroup: "delts", role: "secondary" },
      { muscleGroup: "triceps", role: "secondary" },
    ],
  },
  {
    name: "Lying Leg Curls",
    bodyPosition: "lying",
    laterality: "bilateral",
    movementPattern: "pull",
    equipment: "machine",
    muscles: [{ muscleGroup: "hamstrings", role: "primary" }],
  },
  {
    name: "Lying Pronation",
    bodyPosition: "lying",
    laterality: "unilateral",
    movementPattern: "pull",
    equipment: "dumbbell",
    muscles: [{ muscleGroup: "forearms", role: "primary" }],
  },
  {
    name: "Lying T-Bar Row",
    bodyPosition: "lying",
    laterality: "bilateral",
    movementPattern: "pull",
    equipment: "machine",
    muscles: [
      { muscleGroup: "back", role: "primary" },
      { muscleGroup: "biceps", role: "secondary" },
    ],
  },
  {
    name: "Machine Preacher Curl",
    bodyPosition: "seated",
    laterality: "bilateral",
    movementPattern: "pull",
    equipment: "machine",
    muscles: [{ muscleGroup: "biceps", role: "primary" }],
  },
  {
    name: "Muscle Up",
    bodyPosition: "hanging",
    laterality: "bilateral",
    movementPattern: "pull",
    muscles: [
      { muscleGroup: "back", role: "primary" },
      { muscleGroup: "biceps", role: "secondary" },
      { muscleGroup: "core", role: "secondary" },
      { muscleGroup: "delts", role: "secondary" },
      { muscleGroup: "forearms", role: "secondary" },
      { muscleGroup: "traps", role: "secondary" },
      { muscleGroup: "triceps", role: "secondary" },
    ],
  },
  {
    name: "One-Arm Long Bar Row",
    bodyPosition: "bent-over",
    laterality: "unilateral",
    movementPattern: "pull",
    equipment: "barbell",
    muscles: [
      { muscleGroup: "back", role: "primary" },
      { muscleGroup: "biceps", role: "secondary" },
    ],
  },
  {
    name: "One-Arm Row",
    bodyPosition: "bent-over",
    laterality: "unilateral",
    movementPattern: "pull",
    equipment: "kettlebell",
    muscles: [
      { muscleGroup: "back", role: "primary" },
      { muscleGroup: "biceps", role: "secondary" },
    ],
  },
  {
    name: "One-Arm Split Jerk",
    bodyPosition: "standing",
    laterality: "unilateral",
    movementPattern: "push",
    equipment: "kettlebell",
    muscles: [
      { muscleGroup: "delts", role: "primary" },
      { muscleGroup: "glutes", role: "secondary" },
      { muscleGroup: "hamstrings", role: "secondary" },
      { muscleGroup: "quads", role: "secondary" },
      { muscleGroup: "triceps", role: "secondary" },
    ],
  },
  {
    name: "One-Arm Split Snatch",
    bodyPosition: "standing",
    laterality: "unilateral",
    movementPattern: "pull",
    equipment: "kettlebell",
    muscles: [
      { muscleGroup: "delts", role: "primary" },
      { muscleGroup: "hamstrings", role: "secondary" },
      { muscleGroup: "quads", role: "secondary" },
    ],
  },
  {
    name: "One-Arm Swings",
    bodyPosition: "standing",
    laterality: "unilateral",
    movementPattern: "hinge",
    equipment: "kettlebell",
    muscles: [
      { muscleGroup: "hamstrings", role: "primary" },
      { muscleGroup: "back", role: "secondary" },
      { muscleGroup: "calves", role: "secondary" },
      { muscleGroup: "delts", role: "secondary" },
      { muscleGroup: "glutes", role: "secondary" },
    ],
  },
  {
    name: "One-Legged Deadlift",
    bodyPosition: "standing",
    laterality: "unilateral",
    movementPattern: "hinge",
    equipment: "kettlebell",
    muscles: [
      { muscleGroup: "hamstrings", role: "primary" },
      { muscleGroup: "back", role: "secondary" },
      { muscleGroup: "glutes", role: "secondary" },
    ],
  },
  {
    name: "One-Legged Kickback",
    bodyPosition: "kneeling",
    laterality: "unilateral",
    movementPattern: "push",
    equipment: "cable",
    muscles: [
      { muscleGroup: "glutes", role: "primary" },
      { muscleGroup: "hamstrings", role: "secondary" },
    ],
  },
  {
    name: "Pallof Press",
    bodyPosition: "standing",
    laterality: "bilateral",
    movementPattern: "core",
    equipment: "cable",
    muscles: [
      { muscleGroup: "core", role: "primary" },
      { muscleGroup: "chest", role: "secondary" },
      { muscleGroup: "delts", role: "secondary" },
      { muscleGroup: "triceps", role: "secondary" },
    ],
  },
  {
    name: "Pallof Press With Rotation",
    bodyPosition: "standing",
    laterality: "bilateral",
    movementPattern: "core",
    equipment: "cable",
    muscles: [
      { muscleGroup: "core", role: "primary" },
      { muscleGroup: "chest", role: "secondary" },
      { muscleGroup: "delts", role: "secondary" },
      { muscleGroup: "triceps", role: "secondary" },
    ],
  },
  {
    name: "Physioball Hip Bridge",
    bodyPosition: "lying",
    laterality: "bilateral",
    movementPattern: "push",
    equipment: "exercise-ball",
    muscles: [
      { muscleGroup: "glutes", role: "primary" },
      { muscleGroup: "hamstrings", role: "secondary" },
    ],
  },
  {
    name: "Pistol Squat",
    bodyPosition: "standing",
    laterality: "unilateral",
    movementPattern: "squat",
    equipment: "kettlebell",
    muscles: [
      { muscleGroup: "quads", role: "primary" },
      { muscleGroup: "calves", role: "secondary" },
      { muscleGroup: "delts", role: "secondary" },
      { muscleGroup: "glutes", role: "secondary" },
      { muscleGroup: "hamstrings", role: "secondary" },
    ],
  },
  {
    name: "Plank",
    bodyPosition: "lying",
    laterality: "bilateral",
    movementPattern: "core",
    equipment: "bodyweight",
    muscles: [{ muscleGroup: "core", role: "primary" }],
  },
  {
    name: "Plyo Pushups",
    bodyPosition: "lying",
    laterality: "bilateral",
    movementPattern: "push",
    equipment: "kettlebell",
    muscles: [
      { muscleGroup: "chest", role: "primary" },
      { muscleGroup: "delts", role: "secondary" },
      { muscleGroup: "triceps", role: "secondary" },
    ],
  },
  {
    name: "Power Clean",
    bodyPosition: "standing",
    laterality: "bilateral",
    movementPattern: "pull",
    equipment: "barbell",
    muscles: [
      { muscleGroup: "hamstrings", role: "primary" },
      { muscleGroup: "back", role: "secondary" },
      { muscleGroup: "calves", role: "secondary" },
      { muscleGroup: "delts", role: "secondary" },
      { muscleGroup: "forearms", role: "secondary" },
      { muscleGroup: "glutes", role: "secondary" },
      { muscleGroup: "quads", role: "secondary" },
      { muscleGroup: "traps", role: "secondary" },
      { muscleGroup: "triceps", role: "secondary" },
    ],
  },
  {
    name: "Power Jerk",
    bodyPosition: "standing",
    laterality: "bilateral",
    movementPattern: "push",
    equipment: "barbell",
    muscles: [
      { muscleGroup: "quads", role: "primary" },
      { muscleGroup: "calves", role: "secondary" },
      { muscleGroup: "core", role: "secondary" },
      { muscleGroup: "delts", role: "secondary" },
      { muscleGroup: "glutes", role: "secondary" },
      { muscleGroup: "hamstrings", role: "secondary" },
      { muscleGroup: "triceps", role: "secondary" },
    ],
  },
  {
    name: "Power Snatch",
    bodyPosition: "standing",
    laterality: "bilateral",
    movementPattern: "pull",
    equipment: "barbell",
    muscles: [
      { muscleGroup: "hamstrings", role: "primary" },
      { muscleGroup: "back", role: "secondary" },
      { muscleGroup: "calves", role: "secondary" },
      { muscleGroup: "delts", role: "secondary" },
      { muscleGroup: "glutes", role: "secondary" },
      { muscleGroup: "quads", role: "secondary" },
      { muscleGroup: "traps", role: "secondary" },
      { muscleGroup: "triceps", role: "secondary" },
    ],
  },
  {
    name: "Press Sit-Up",
    bodyPosition: "lying",
    laterality: "bilateral",
    movementPattern: "core",
    equipment: "barbell",
    muscles: [
      { muscleGroup: "core", role: "primary" },
      { muscleGroup: "chest", role: "secondary" },
      { muscleGroup: "delts", role: "secondary" },
      { muscleGroup: "triceps", role: "secondary" },
    ],
  },
  {
    name: "Pull Apart",
    bodyPosition: "standing",
    laterality: "bilateral",
    movementPattern: "pull",
    equipment: "band",
    muscles: [
      { muscleGroup: "delts", role: "primary" },
      { muscleGroup: "back", role: "secondary" },
      { muscleGroup: "traps", role: "secondary" },
    ],
  },
  {
    name: "Pull Through",
    bodyPosition: "standing",
    laterality: "bilateral",
    movementPattern: "pull",
    equipment: "cable",
    muscles: [
      { muscleGroup: "glutes", role: "primary" },
      { muscleGroup: "back", role: "secondary" },
      { muscleGroup: "hamstrings", role: "secondary" },
    ],
  },
  {
    name: "Pull-In",
    bodyPosition: "seated",
    laterality: "bilateral",
    rangeOfMotion: "partial",
    movementPattern: "core",
    equipment: "exercise-ball",
    muscles: [{ muscleGroup: "core", role: "primary" }],
  },
  {
    name: "Pullups",
    bodyPosition: "hanging",
    laterality: "bilateral",
    movementPattern: "pull",
    equipment: "bodyweight",
    muscles: [
      { muscleGroup: "back", role: "primary" },
      { muscleGroup: "biceps", role: "secondary" },
    ],
  },
  {
    name: "Push-Ups (Feet Elevated)",
    bodyPosition: "decline",
    laterality: "bilateral",
    movementPattern: "push",
    equipment: "exercise-ball",
    muscles: [
      { muscleGroup: "chest", role: "primary" },
      { muscleGroup: "delts", role: "secondary" },
      { muscleGroup: "triceps", role: "secondary" },
    ],
  },
  {
    name: "Pushups",
    bodyPosition: "lying",
    laterality: "bilateral",
    movementPattern: "push",
    equipment: "bodyweight",
    muscles: [
      { muscleGroup: "chest", role: "primary" },
      { muscleGroup: "delts", role: "secondary" },
      { muscleGroup: "triceps", role: "secondary" },
    ],
  },
  {
    name: "Rack Pulls",
    bodyPosition: "standing",
    laterality: "bilateral",
    rangeOfMotion: "pin",
    movementPattern: "pull",
    equipment: "barbell",
    muscles: [
      { muscleGroup: "back", role: "primary" },
      { muscleGroup: "forearms", role: "secondary" },
      { muscleGroup: "glutes", role: "secondary" },
      { muscleGroup: "hamstrings", role: "secondary" },
      { muscleGroup: "traps", role: "secondary" },
    ],
  },
  {
    name: "Raise",
    bodyPosition: "standing",
    laterality: "bilateral",
    movementPattern: "pull",
    equipment: "dumbbell",
    muscles: [
      { muscleGroup: "delts", role: "primary" },
      { muscleGroup: "biceps", role: "secondary" },
    ],
  },
  {
    name: "Rear Delt Fly",
    bodyPosition: "bent-over",
    laterality: "bilateral",
    movementPattern: "pull",
    equipment: "cable",
    muscles: [{ muscleGroup: "delts", role: "primary" }],
  },
  {
    name: "Rear Delt Row",
    bodyPosition: "bent-over",
    laterality: "bilateral",
    movementPattern: "pull",
    equipment: "barbell",
    muscles: [
      { muscleGroup: "delts", role: "primary" },
      { muscleGroup: "back", role: "secondary" },
      { muscleGroup: "biceps", role: "secondary" },
    ],
  },
  {
    name: "Reverse Crunch",
    bodyPosition: "lying",
    laterality: "bilateral",
    movementPattern: "core",
    equipment: "bodyweight",
    muscles: [{ muscleGroup: "core", role: "primary" }],
  },
  {
    name: "Reverse Curl",
    bodyPosition: "standing",
    laterality: "bilateral",
    gripOrientation: "pronated",
    movementPattern: "pull",
    equipment: "cable",
    muscles: [
      { muscleGroup: "biceps", role: "primary" },
      { muscleGroup: "forearms", role: "secondary" },
    ],
  },
  {
    name: "Reverse Flyes",
    bodyPosition: "bent-over",
    laterality: "bilateral",
    movementPattern: "pull",
    equipment: "dumbbell",
    muscles: [{ muscleGroup: "delts", role: "primary" }],
  },
  {
    name: "Reverse Hyperextension",
    bodyPosition: "lying",
    laterality: "bilateral",
    movementPattern: "hinge",
    equipment: "machine",
    muscles: [
      { muscleGroup: "hamstrings", role: "primary" },
      { muscleGroup: "calves", role: "secondary" },
      { muscleGroup: "glutes", role: "secondary" },
    ],
  },
  {
    name: "Reverse Preacher Curls",
    bodyPosition: "seated",
    laterality: "bilateral",
    gripOrientation: "pronated",
    movementPattern: "pull",
    equipment: "ez-bar",
    muscles: [
      { muscleGroup: "biceps", role: "primary" },
      { muscleGroup: "forearms", role: "secondary" },
    ],
  },
  {
    name: "Ring Dips",
    bodyPosition: "hanging",
    laterality: "bilateral",
    movementPattern: "push",
    muscles: [
      { muscleGroup: "triceps", role: "primary" },
      { muscleGroup: "chest", role: "secondary" },
      { muscleGroup: "delts", role: "secondary" },
    ],
  },
  {
    name: "Romanian Deadlift",
    bodyPosition: "standing",
    laterality: "bilateral",
    movementPattern: "hinge",
    equipment: "barbell",
    muscles: [
      { muscleGroup: "hamstrings", role: "primary" },
      { muscleGroup: "back", role: "secondary" },
      { muscleGroup: "calves", role: "secondary" },
      { muscleGroup: "glutes", role: "secondary" },
    ],
  },
  {
    name: "Rope Crunch",
    bodyPosition: "kneeling",
    laterality: "bilateral",
    movementPattern: "core",
    equipment: "cable",
    muscles: [{ muscleGroup: "core", role: "primary" }],
  },
  {
    name: "Rope Overhead Triceps Extension",
    bodyPosition: "standing",
    laterality: "bilateral",
    movementPattern: "push",
    equipment: "cable",
    muscles: [{ muscleGroup: "triceps", role: "primary" }],
  },
  {
    name: "Rope Rear-Delt Rows",
    bodyPosition: "standing",
    laterality: "bilateral",
    movementPattern: "pull",
    equipment: "cable",
    muscles: [
      { muscleGroup: "delts", role: "primary" },
      { muscleGroup: "back", role: "secondary" },
      { muscleGroup: "biceps", role: "secondary" },
    ],
  },
  {
    name: "Seated Calf Raise",
    bodyPosition: "seated",
    laterality: "bilateral",
    movementPattern: "push",
    equipment: "barbell",
    muscles: [{ muscleGroup: "calves", role: "primary" }],
  },
  {
    name: "Seated Hamstring Curl",
    bodyPosition: "seated",
    laterality: "bilateral",
    movementPattern: "pull",
    equipment: "band",
    muscles: [{ muscleGroup: "hamstrings", role: "primary" }],
  },
  {
    name: "Seated Lateral Raise",
    bodyPosition: "seated",
    laterality: "bilateral",
    movementPattern: "pull",
    equipment: "cable",
    muscles: [
      { muscleGroup: "delts", role: "primary" },
      { muscleGroup: "back", role: "secondary" },
      { muscleGroup: "traps", role: "secondary" },
    ],
  },
  {
    name: "Seated Leg Tucks",
    bodyPosition: "seated",
    laterality: "bilateral",
    movementPattern: "core",
    equipment: "bodyweight",
    muscles: [{ muscleGroup: "core", role: "primary" }],
  },
  {
    name: "Seated Rows",
    bodyPosition: "seated",
    laterality: "bilateral",
    movementPattern: "pull",
    equipment: "cable",
    muscles: [
      { muscleGroup: "back", role: "primary" },
      { muscleGroup: "biceps", role: "secondary" },
      { muscleGroup: "delts", role: "secondary" },
    ],
  },
  {
    name: "Shoulder Press",
    bodyPosition: "seated",
    laterality: "bilateral",
    movementPattern: "push",
    equipment: "barbell",
    muscles: [
      { muscleGroup: "delts", role: "primary" },
      { muscleGroup: "chest", role: "secondary" },
      { muscleGroup: "triceps", role: "secondary" },
    ],
  },
  {
    name: "Side Bend",
    bodyPosition: "standing",
    laterality: "unilateral",
    movementPattern: "core",
    equipment: "barbell",
    muscles: [
      { muscleGroup: "core", role: "primary" },
      { muscleGroup: "back", role: "secondary" },
    ],
  },
  {
    name: "Side Split Squat",
    bodyPosition: "standing",
    laterality: "unilateral",
    movementPattern: "squat",
    equipment: "barbell",
    muscles: [
      { muscleGroup: "quads", role: "primary" },
      { muscleGroup: "back", role: "secondary" },
      { muscleGroup: "calves", role: "secondary" },
      { muscleGroup: "hamstrings", role: "secondary" },
    ],
  },
  {
    name: "Single Leg Push-off",
    bodyPosition: "standing",
    laterality: "unilateral",
    movementPattern: "push",
    muscles: [
      { muscleGroup: "quads", role: "primary" },
      { muscleGroup: "calves", role: "secondary" },
      { muscleGroup: "hamstrings", role: "secondary" },
    ],
  },
  {
    name: "Sit-Up",
    bodyPosition: "lying",
    laterality: "bilateral",
    movementPattern: "core",
    equipment: "bodyweight",
    muscles: [{ muscleGroup: "core", role: "primary" }],
  },
  {
    name: "Smith Single-Leg Split Squat",
    bodyPosition: "standing",
    laterality: "unilateral",
    movementPattern: "squat",
    equipment: "machine",
    muscles: [
      { muscleGroup: "quads", role: "primary" },
      { muscleGroup: "calves", role: "secondary" },
      { muscleGroup: "glutes", role: "secondary" },
      { muscleGroup: "hamstrings", role: "secondary" },
    ],
  },
  {
    name: "Snatch",
    bodyPosition: "standing",
    laterality: "bilateral",
    movementPattern: "pull",
    equipment: "barbell",
    muscles: [
      { muscleGroup: "quads", role: "primary" },
      { muscleGroup: "back", role: "secondary" },
      { muscleGroup: "biceps", role: "secondary" },
      { muscleGroup: "delts", role: "secondary" },
      { muscleGroup: "glutes", role: "secondary" },
      { muscleGroup: "hamstrings", role: "secondary" },
      { muscleGroup: "traps", role: "secondary" },
      { muscleGroup: "triceps", role: "secondary" },
    ],
  },
  {
    name: "Spider Curl",
    bodyPosition: "incline",
    laterality: "bilateral",
    movementPattern: "pull",
    equipment: "ez-bar",
    muscles: [{ muscleGroup: "biceps", role: "primary" }],
  },
  {
    name: "Split Clean",
    bodyPosition: "standing",
    laterality: "bilateral",
    movementPattern: "pull",
    equipment: "barbell",
    muscles: [
      { muscleGroup: "quads", role: "primary" },
      { muscleGroup: "back", role: "secondary" },
      { muscleGroup: "calves", role: "secondary" },
      { muscleGroup: "delts", role: "secondary" },
      { muscleGroup: "forearms", role: "secondary" },
      { muscleGroup: "glutes", role: "secondary" },
      { muscleGroup: "hamstrings", role: "secondary" },
      { muscleGroup: "traps", role: "secondary" },
    ],
  },
  {
    name: "Split Jerk",
    bodyPosition: "standing",
    laterality: "bilateral",
    movementPattern: "push",
    equipment: "barbell",
    muscles: [
      { muscleGroup: "quads", role: "primary" },
      { muscleGroup: "delts", role: "secondary" },
      { muscleGroup: "glutes", role: "secondary" },
      { muscleGroup: "hamstrings", role: "secondary" },
      { muscleGroup: "triceps", role: "secondary" },
    ],
  },
  {
    name: "Split Snatch",
    bodyPosition: "standing",
    laterality: "bilateral",
    movementPattern: "pull",
    equipment: "barbell",
    muscles: [
      { muscleGroup: "hamstrings", role: "primary" },
      { muscleGroup: "back", role: "secondary" },
      { muscleGroup: "calves", role: "secondary" },
      { muscleGroup: "delts", role: "secondary" },
      { muscleGroup: "forearms", role: "secondary" },
      { muscleGroup: "glutes", role: "secondary" },
      { muscleGroup: "quads", role: "secondary" },
      { muscleGroup: "traps", role: "secondary" },
      { muscleGroup: "triceps", role: "secondary" },
    ],
  },
  {
    name: "Split Squat",
    bodyPosition: "standing",
    laterality: "unilateral",
    movementPattern: "squat",
    equipment: "dumbbell",
    muscles: [
      { muscleGroup: "quads", role: "primary" },
      { muscleGroup: "glutes", role: "secondary" },
      { muscleGroup: "hamstrings", role: "secondary" },
    ],
  },
  {
    name: "Squat",
    bodyPosition: "standing",
    laterality: "bilateral",
    movementPattern: "squat",
    equipment: "bodyweight",
    muscles: [
      { muscleGroup: "quads", role: "primary" },
      { muscleGroup: "back", role: "secondary" },
      { muscleGroup: "calves", role: "secondary" },
      { muscleGroup: "glutes", role: "secondary" },
      { muscleGroup: "hamstrings", role: "secondary" },
    ],
  },
  {
    name: "Standing Low-Pulley One-Arm Triceps Extension",
    bodyPosition: "standing",
    laterality: "unilateral",
    movementPattern: "push",
    equipment: "cable",
    muscles: [
      { muscleGroup: "triceps", role: "primary" },
      { muscleGroup: "chest", role: "secondary" },
      { muscleGroup: "delts", role: "secondary" },
    ],
  },
  {
    name: "Standing Overhead Triceps Extension",
    bodyPosition: "standing",
    laterality: "bilateral",
    movementPattern: "push",
    equipment: "barbell",
    muscles: [
      { muscleGroup: "triceps", role: "primary" },
      { muscleGroup: "delts", role: "secondary" },
    ],
  },
  {
    name: "Standing Towel Triceps Extension",
    bodyPosition: "standing",
    laterality: "bilateral",
    movementPattern: "push",
    equipment: "bodyweight",
    muscles: [{ muscleGroup: "triceps", role: "primary" }],
  },
  {
    name: "Standing Upright Row",
    bodyPosition: "standing",
    laterality: "bilateral",
    movementPattern: "pull",
    equipment: "dumbbell",
    muscles: [
      { muscleGroup: "traps", role: "primary" },
      { muscleGroup: "biceps", role: "secondary" },
      { muscleGroup: "delts", role: "secondary" },
    ],
  },
  {
    name: "Stiff-Legged Deadlift",
    bodyPosition: "standing",
    laterality: "bilateral",
    movementPattern: "hinge",
    equipment: "dumbbell",
    muscles: [
      { muscleGroup: "hamstrings", role: "primary" },
      { muscleGroup: "back", role: "secondary" },
      { muscleGroup: "glutes", role: "secondary" },
    ],
  },
  {
    name: "Straight-Arm Pulldown",
    bodyPosition: "standing",
    laterality: "bilateral",
    gripOrientation: "pronated",
    movementPattern: "pull",
    equipment: "cable",
    muscles: [{ muscleGroup: "back", role: "primary" }],
  },
  {
    name: "Suspended Split Squat",
    bodyPosition: "standing",
    laterality: "unilateral",
    movementPattern: "squat",
    muscles: [
      { muscleGroup: "quads", role: "primary" },
      { muscleGroup: "calves", role: "secondary" },
      { muscleGroup: "glutes", role: "secondary" },
      { muscleGroup: "hamstrings", role: "secondary" },
    ],
  },
  {
    name: "Thigh Abductor",
    bodyPosition: "seated",
    laterality: "bilateral",
    movementPattern: "push",
    equipment: "machine",
    muscles: [{ muscleGroup: "glutes", role: "primary" }],
  },
  {
    name: "Thruster",
    bodyPosition: "standing",
    laterality: "bilateral",
    movementPattern: "push",
    equipment: "kettlebell",
    muscles: [
      { muscleGroup: "delts", role: "primary" },
      { muscleGroup: "quads", role: "secondary" },
      { muscleGroup: "triceps", role: "secondary" },
    ],
  },
  {
    name: "Tricep Kickback",
    bodyPosition: "bent-over",
    laterality: "unilateral",
    movementPattern: "push",
    equipment: "dumbbell",
    muscles: [{ muscleGroup: "triceps", role: "primary" }],
  },
  {
    name: "Triceps Extension",
    bodyPosition: "standing",
    laterality: "bilateral",
    movementPattern: "push",
    equipment: "machine",
    muscles: [{ muscleGroup: "triceps", role: "primary" }],
  },
  {
    name: "Triceps Pushdown",
    bodyPosition: "standing",
    laterality: "bilateral",
    movementPattern: "push",
    equipment: "cable",
    muscles: [{ muscleGroup: "triceps", role: "primary" }],
  },
  {
    name: "Turkish Get-Up (Lunge style)",
    bodyPosition: "lying",
    laterality: "unilateral",
    movementPattern: "lunge",
    equipment: "kettlebell",
    muscles: [
      { muscleGroup: "delts", role: "primary" },
      { muscleGroup: "core", role: "secondary" },
      { muscleGroup: "hamstrings", role: "secondary" },
      { muscleGroup: "quads", role: "secondary" },
      { muscleGroup: "triceps", role: "secondary" },
    ],
  },
  {
    name: "Turkish Get-Up (Squat style)",
    bodyPosition: "lying",
    laterality: "unilateral",
    movementPattern: "squat",
    equipment: "kettlebell",
    muscles: [
      { muscleGroup: "delts", role: "primary" },
      { muscleGroup: "calves", role: "secondary" },
      { muscleGroup: "core", role: "secondary" },
      { muscleGroup: "hamstrings", role: "secondary" },
      { muscleGroup: "quads", role: "secondary" },
      { muscleGroup: "triceps", role: "secondary" },
    ],
  },
  {
    name: "Upright Row",
    bodyPosition: "standing",
    laterality: "bilateral",
    movementPattern: "pull",
    equipment: "barbell",
    muscles: [
      { muscleGroup: "delts", role: "primary" },
      { muscleGroup: "traps", role: "primary" },
      { muscleGroup: "back", role: "secondary" },
      { muscleGroup: "biceps", role: "secondary" },
    ],
  },
  {
    name: "Walking Lunge",
    bodyPosition: "standing",
    laterality: "alternating",
    movementPattern: "lunge",
    equipment: "bodyweight",
    muscles: [
      { muscleGroup: "quads", role: "primary" },
      { muscleGroup: "calves", role: "secondary" },
      { muscleGroup: "glutes", role: "secondary" },
      { muscleGroup: "hamstrings", role: "secondary" },
    ],
  },
  {
    name: "Weighted Crunches",
    bodyPosition: "lying",
    laterality: "bilateral",
    movementPattern: "core",
    equipment: "medicine-ball",
    muscles: [{ muscleGroup: "core", role: "primary" }],
  },
  {
    name: "Weighted Hyperextension",
    bodyPosition: "bent-over",
    laterality: "bilateral",
    movementPattern: "hinge",
    equipment: "exercise-ball",
    muscles: [
      { muscleGroup: "back", role: "primary" },
      { muscleGroup: "glutes", role: "secondary" },
      { muscleGroup: "hamstrings", role: "secondary" },
    ],
  },
  {
    name: "Weighted Side Bend",
    bodyPosition: "standing",
    laterality: "unilateral",
    movementPattern: "core",
    equipment: "exercise-ball",
    muscles: [{ muscleGroup: "core", role: "primary" }],
  },
  {
    name: "Wrist Curl",
    bodyPosition: "seated",
    laterality: "bilateral",
    movementPattern: "pull",
    equipment: "cable",
    muscles: [{ muscleGroup: "forearms", role: "primary" }],
  },
  {
    name: "Wrist Roller",
    bodyPosition: "standing",
    laterality: "bilateral",
    movementPattern: "pull",
    muscles: [
      { muscleGroup: "forearms", role: "primary" },
      { muscleGroup: "delts", role: "secondary" },
    ],
  },
  {
    name: "Zottman Preacher Curl",
    bodyPosition: "seated",
    laterality: "bilateral",
    movementPattern: "pull",
    equipment: "dumbbell",
    muscles: [
      { muscleGroup: "biceps", role: "primary" },
      { muscleGroup: "forearms", role: "secondary" },
    ],
  },
];
