// Curated exercise library. Originally derived from free-exercise-db
// (https://github.com/yuhonas/free-exercise-db), then condensed: grip/angle
// variants folded into their base movement, and equipment names stripped from
// exercise names (equipment lives in the `equipment` field instead), merging
// any entries that collided as a result.
import type { SeedExercise } from "./types.js";

export const SEED_EXERCISES: SeedExercise[] = [
  {
    name: "Ab Crunch",
    movementPattern: "core",
    equipment: "machine",
    muscles: [{ muscleGroup: "core", role: "primary" }],
  },
  {
    name: "Ab Roller",
    movementPattern: "core",
    muscles: [
      { muscleGroup: "core", role: "primary" },
      { muscleGroup: "delts", role: "secondary" },
    ],
  },
  {
    name: "Ab Rollout",
    movementPattern: "core",
    equipment: "barbell",
    muscles: [
      { muscleGroup: "core", role: "primary" },
      { muscleGroup: "back", role: "secondary" },
      { muscleGroup: "delts", role: "secondary" },
    ],
  },
  {
    name: "Arnold Press",
    movementPattern: "push",
    equipment: "kettlebell",
    muscles: [
      { muscleGroup: "delts", role: "primary" },
      { muscleGroup: "triceps", role: "secondary" },
    ],
  },
  {
    name: "Bench Dips",
    movementPattern: "push",
    equipment: "bodyweight",
    muscles: [
      { muscleGroup: "triceps", role: "primary" },
      { muscleGroup: "chest", role: "secondary" },
      { muscleGroup: "delts", role: "secondary" },
    ],
  },
  {
    name: "Bench Press",
    movementPattern: "push",
    equipment: "barbell",
    muscles: [
      { muscleGroup: "chest", role: "primary" },
      { muscleGroup: "delts", role: "secondary" },
      { muscleGroup: "triceps", role: "secondary" },
    ],
  },
  {
    name: "Bent Over Row",
    movementPattern: "pull",
    equipment: "barbell",
    muscles: [
      { muscleGroup: "back", role: "primary" },
      { muscleGroup: "biceps", role: "secondary" },
      { muscleGroup: "delts", role: "secondary" },
    ],
  },
  {
    name: "Bent-Arm Pullover",
    movementPattern: "pull",
    equipment: "barbell",
    muscles: [
      { muscleGroup: "back", role: "primary" },
      { muscleGroup: "chest", role: "primary" },
      { muscleGroup: "delts", role: "secondary" },
      { muscleGroup: "triceps", role: "secondary" },
    ],
  },
  {
    name: "Bicep Curl",
    movementPattern: "pull",
    equipment: "dumbbell",
    muscles: [
      { muscleGroup: "biceps", role: "primary" },
      { muscleGroup: "forearms", role: "secondary" },
    ],
  },
  {
    name: "Body Tricep Press",
    movementPattern: "push",
    equipment: "bodyweight",
    muscles: [{ muscleGroup: "triceps", role: "primary" }],
  },
  {
    name: "Butt Lift (Bridge)",
    movementPattern: "push",
    equipment: "bodyweight",
    muscles: [
      { muscleGroup: "glutes", role: "primary" },
      { muscleGroup: "hamstrings", role: "secondary" },
    ],
  },
  {
    name: "Butterfly",
    movementPattern: "pull",
    equipment: "machine",
    muscles: [{ muscleGroup: "chest", role: "primary" }],
  },
  {
    name: "Calf Press",
    movementPattern: "push",
    equipment: "machine",
    muscles: [{ muscleGroup: "calves", role: "primary" }],
  },
  {
    name: "Chest Pass",
    movementPattern: "push",
    equipment: "medicine-ball",
    muscles: [
      { muscleGroup: "chest", role: "primary" },
      { muscleGroup: "delts", role: "secondary" },
      { muscleGroup: "triceps", role: "secondary" },
    ],
  },
  {
    name: "Chest Press",
    movementPattern: "push",
    equipment: "cable",
    muscles: [
      { muscleGroup: "chest", role: "primary" },
      { muscleGroup: "delts", role: "secondary" },
      { muscleGroup: "triceps", role: "secondary" },
    ],
  },
  {
    name: "Clean",
    movementPattern: "pull",
    equipment: "barbell",
    muscles: [
      { muscleGroup: "hamstrings", role: "primary" },
      { muscleGroup: "back", role: "secondary" },
      { muscleGroup: "calves", role: "secondary" },
      { muscleGroup: "delts", role: "secondary" },
      { muscleGroup: "forearms", role: "secondary" },
      { muscleGroup: "glutes", role: "secondary" },
      { muscleGroup: "quads", role: "secondary" },
      { muscleGroup: "traps", role: "secondary" },
    ],
  },
  {
    name: "Concentration Curls",
    movementPattern: "pull",
    equipment: "dumbbell",
    muscles: [
      { muscleGroup: "biceps", role: "primary" },
      { muscleGroup: "forearms", role: "secondary" },
    ],
  },
  {
    name: "Crossover",
    movementPattern: "push",
    equipment: "cable",
    muscles: [
      { muscleGroup: "chest", role: "primary" },
      { muscleGroup: "delts", role: "secondary" },
    ],
  },
  {
    name: "Crunch",
    movementPattern: "core",
    equipment: "cable",
    muscles: [{ muscleGroup: "core", role: "primary" }],
  },
  {
    name: "Curl",
    movementPattern: "pull",
    equipment: "barbell",
    muscles: [
      { muscleGroup: "biceps", role: "primary" },
      { muscleGroup: "forearms", role: "secondary" },
    ],
  },
  {
    name: "Dead Bug",
    movementPattern: "core",
    equipment: "bodyweight",
    muscles: [{ muscleGroup: "core", role: "primary" }],
  },
  {
    name: "Dead Clean",
    movementPattern: "pull",
    equipment: "kettlebell",
    muscles: [
      { muscleGroup: "hamstrings", role: "primary" },
      { muscleGroup: "back", role: "secondary" },
      { muscleGroup: "calves", role: "secondary" },
      { muscleGroup: "glutes", role: "secondary" },
      { muscleGroup: "quads", role: "secondary" },
      { muscleGroup: "traps", role: "secondary" },
    ],
  },
  {
    name: "Deadlift",
    movementPattern: "hinge",
    equipment: "barbell",
    muscles: [
      { muscleGroup: "back", role: "primary" },
      { muscleGroup: "quads", role: "primary" },
      { muscleGroup: "calves", role: "secondary" },
      { muscleGroup: "forearms", role: "secondary" },
      { muscleGroup: "glutes", role: "secondary" },
      { muscleGroup: "hamstrings", role: "secondary" },
      { muscleGroup: "traps", role: "secondary" },
    ],
  },
  {
    name: "Deadlifts",
    movementPattern: "hinge",
    equipment: "cable",
    muscles: [
      { muscleGroup: "quads", role: "primary" },
      { muscleGroup: "back", role: "secondary" },
      { muscleGroup: "forearms", role: "secondary" },
      { muscleGroup: "glutes", role: "secondary" },
      { muscleGroup: "hamstrings", role: "secondary" },
    ],
  },
  {
    name: "Decline Crunch",
    movementPattern: "core",
    equipment: "bodyweight",
    muscles: [{ muscleGroup: "core", role: "primary" }],
  },
  {
    name: "Dip",
    movementPattern: "push",
    equipment: "machine",
    muscles: [
      { muscleGroup: "triceps", role: "primary" },
      { muscleGroup: "chest", role: "secondary" },
      { muscleGroup: "delts", role: "secondary" },
    ],
  },
  {
    name: "Donkey Calf Raises",
    movementPattern: "push",
    muscles: [{ muscleGroup: "calves", role: "primary" }],
  },
  {
    name: "Double Jerk",
    movementPattern: "push",
    equipment: "kettlebell",
    muscles: [
      { muscleGroup: "delts", role: "primary" },
      { muscleGroup: "calves", role: "secondary" },
      { muscleGroup: "quads", role: "secondary" },
      { muscleGroup: "triceps", role: "secondary" },
    ],
  },
  {
    name: "Double Snatch",
    movementPattern: "pull",
    equipment: "kettlebell",
    muscles: [
      { muscleGroup: "delts", role: "primary" },
      { muscleGroup: "glutes", role: "secondary" },
      { muscleGroup: "hamstrings", role: "secondary" },
      { muscleGroup: "quads", role: "secondary" },
    ],
  },
  {
    name: "Face Pull",
    movementPattern: "pull",
    equipment: "cable",
    muscles: [
      { muscleGroup: "delts", role: "primary" },
      { muscleGroup: "back", role: "secondary" },
    ],
  },
  {
    name: "Farmer's Walk",
    movementPattern: "carry",
    muscles: [
      { muscleGroup: "forearms", role: "primary" },
      { muscleGroup: "back", role: "secondary" },
      { muscleGroup: "core", role: "secondary" },
      { muscleGroup: "glutes", role: "secondary" },
      { muscleGroup: "hamstrings", role: "secondary" },
      { muscleGroup: "quads", role: "secondary" },
      { muscleGroup: "traps", role: "secondary" },
    ],
  },
  {
    name: "Flyes",
    movementPattern: "push",
    equipment: "dumbbell",
    muscles: [
      { muscleGroup: "chest", role: "primary" },
      { muscleGroup: "core", role: "secondary" },
      { muscleGroup: "delts", role: "secondary" },
      { muscleGroup: "triceps", role: "secondary" },
    ],
  },
  {
    name: "Front Raise",
    movementPattern: "push",
    equipment: "dumbbell",
    muscles: [{ muscleGroup: "delts", role: "primary" }],
  },
  {
    name: "Front Raise And Pullover",
    movementPattern: "pull",
    equipment: "barbell",
    muscles: [
      { muscleGroup: "chest", role: "primary" },
      { muscleGroup: "back", role: "secondary" },
      { muscleGroup: "delts", role: "secondary" },
      { muscleGroup: "triceps", role: "secondary" },
    ],
  },
  {
    name: "Full Twist",
    movementPattern: "core",
    equipment: "medicine-ball",
    muscles: [
      { muscleGroup: "core", role: "primary" },
      { muscleGroup: "delts", role: "secondary" },
    ],
  },
  {
    name: "Glute Ham Raise",
    movementPattern: "pull",
    equipment: "machine",
    muscles: [
      { muscleGroup: "hamstrings", role: "primary" },
      { muscleGroup: "calves", role: "secondary" },
      { muscleGroup: "glutes", role: "secondary" },
    ],
  },
  {
    name: "Glute Kickback",
    movementPattern: "push",
    equipment: "bodyweight",
    muscles: [
      { muscleGroup: "glutes", role: "primary" },
      { muscleGroup: "hamstrings", role: "secondary" },
    ],
  },
  {
    name: "Goblet Squat",
    movementPattern: "squat",
    equipment: "kettlebell",
    muscles: [
      { muscleGroup: "quads", role: "primary" },
      { muscleGroup: "calves", role: "secondary" },
      { muscleGroup: "delts", role: "secondary" },
      { muscleGroup: "glutes", role: "secondary" },
      { muscleGroup: "hamstrings", role: "secondary" },
    ],
  },
  {
    name: "Good Morning",
    movementPattern: "hinge",
    equipment: "barbell",
    muscles: [
      { muscleGroup: "hamstrings", role: "primary" },
      { muscleGroup: "back", role: "secondary" },
      { muscleGroup: "core", role: "secondary" },
      { muscleGroup: "glutes", role: "secondary" },
    ],
  },
  {
    name: "Hack Squat",
    movementPattern: "squat",
    equipment: "barbell",
    muscles: [
      { muscleGroup: "quads", role: "primary" },
      { muscleGroup: "calves", role: "secondary" },
      { muscleGroup: "forearms", role: "secondary" },
      { muscleGroup: "glutes", role: "secondary" },
      { muscleGroup: "hamstrings", role: "secondary" },
    ],
  },
  {
    name: "Hammer Curls",
    movementPattern: "pull",
    equipment: "dumbbell",
    muscles: [{ muscleGroup: "biceps", role: "primary" }],
  },
  {
    name: "Hammer Curls - Rope Attachment",
    movementPattern: "pull",
    equipment: "cable",
    muscles: [{ muscleGroup: "biceps", role: "primary" }],
  },
  {
    name: "Hang Clean",
    movementPattern: "pull",
    equipment: "barbell",
    muscles: [
      { muscleGroup: "hamstrings", role: "primary" },
      { muscleGroup: "quads", role: "primary" },
      { muscleGroup: "back", role: "secondary" },
      { muscleGroup: "calves", role: "secondary" },
      { muscleGroup: "delts", role: "secondary" },
      { muscleGroup: "forearms", role: "secondary" },
      { muscleGroup: "glutes", role: "secondary" },
      { muscleGroup: "traps", role: "secondary" },
    ],
  },
  {
    name: "Hang Power Clean",
    movementPattern: "pull",
    equipment: "machine",
    muscles: [
      { muscleGroup: "hamstrings", role: "primary" },
      { muscleGroup: "back", role: "secondary" },
      { muscleGroup: "delts", role: "secondary" },
      { muscleGroup: "glutes", role: "secondary" },
      { muscleGroup: "quads", role: "secondary" },
      { muscleGroup: "traps", role: "secondary" },
    ],
  },
  {
    name: "Hang Snatch",
    movementPattern: "pull",
    equipment: "barbell",
    muscles: [
      { muscleGroup: "hamstrings", role: "primary" },
      { muscleGroup: "back", role: "secondary" },
      { muscleGroup: "calves", role: "secondary" },
      { muscleGroup: "core", role: "secondary" },
      { muscleGroup: "delts", role: "secondary" },
      { muscleGroup: "forearms", role: "secondary" },
      { muscleGroup: "glutes", role: "secondary" },
      { muscleGroup: "quads", role: "secondary" },
      { muscleGroup: "traps", role: "secondary" },
    ],
  },
  {
    name: "Hanging Leg Raise",
    movementPattern: "core",
    equipment: "bodyweight",
    muscles: [{ muscleGroup: "core", role: "primary" }],
  },
  {
    name: "Hanging Pike",
    movementPattern: "core",
    equipment: "bodyweight",
    muscles: [{ muscleGroup: "core", role: "primary" }],
  },
  {
    name: "High Curls",
    movementPattern: "pull",
    equipment: "cable",
    muscles: [{ muscleGroup: "biceps", role: "primary" }],
  },
  {
    name: "Hip Adduction",
    movementPattern: "pull",
    equipment: "cable",
    muscles: [{ muscleGroup: "quads", role: "primary" }],
  },
  {
    name: "Hip Adductions",
    movementPattern: "pull",
    equipment: "band",
    muscles: [{ muscleGroup: "glutes", role: "primary" }],
  },
  {
    name: "Hip Thrust",
    movementPattern: "hinge",
    equipment: "barbell",
    muscles: [
      { muscleGroup: "glutes", role: "primary" },
      { muscleGroup: "calves", role: "secondary" },
      { muscleGroup: "hamstrings", role: "secondary" },
    ],
  },
  {
    name: "Hyperextensions (Back Extensions)",
    movementPattern: "hinge",
    muscles: [
      { muscleGroup: "back", role: "primary" },
      { muscleGroup: "glutes", role: "secondary" },
      { muscleGroup: "hamstrings", role: "secondary" },
    ],
  },
  {
    name: "Incline Row",
    movementPattern: "pull",
    equipment: "dumbbell",
    muscles: [
      { muscleGroup: "back", role: "primary" },
      { muscleGroup: "biceps", role: "secondary" },
      { muscleGroup: "delts", role: "secondary" },
      { muscleGroup: "forearms", role: "secondary" },
    ],
  },
  {
    name: "Inverted Row",
    movementPattern: "pull",
    equipment: "bodyweight",
    muscles: [{ muscleGroup: "back", role: "primary" }],
  },
  {
    name: "Iso Row",
    movementPattern: "pull",
    equipment: "machine",
    muscles: [
      { muscleGroup: "back", role: "primary" },
      { muscleGroup: "biceps", role: "secondary" },
    ],
  },
  {
    name: "Lat Pulldown",
    movementPattern: "pull",
    equipment: "cable",
    muscles: [
      { muscleGroup: "back", role: "primary" },
      { muscleGroup: "biceps", role: "secondary" },
      { muscleGroup: "delts", role: "secondary" },
    ],
  },
  {
    name: "Leg Curl",
    movementPattern: "pull",
    equipment: "exercise-ball",
    muscles: [
      { muscleGroup: "hamstrings", role: "primary" },
      { muscleGroup: "calves", role: "secondary" },
      { muscleGroup: "glutes", role: "secondary" },
    ],
  },
  {
    name: "Leg Extensions",
    movementPattern: "push",
    equipment: "machine",
    muscles: [{ muscleGroup: "quads", role: "primary" }],
  },
  {
    name: "Leg Lift",
    movementPattern: "push",
    equipment: "bodyweight",
    muscles: [
      { muscleGroup: "glutes", role: "primary" },
      { muscleGroup: "hamstrings", role: "secondary" },
    ],
  },
  {
    name: "Leg Press",
    movementPattern: "push",
    equipment: "machine",
    muscles: [
      { muscleGroup: "quads", role: "primary" },
      { muscleGroup: "calves", role: "secondary" },
      { muscleGroup: "glutes", role: "secondary" },
      { muscleGroup: "hamstrings", role: "secondary" },
    ],
  },
  {
    name: "Leg-Over Floor Press",
    movementPattern: "push",
    equipment: "kettlebell",
    muscles: [
      { muscleGroup: "chest", role: "primary" },
      { muscleGroup: "delts", role: "secondary" },
      { muscleGroup: "triceps", role: "secondary" },
    ],
  },
  {
    name: "Lunge",
    movementPattern: "lunge",
    equipment: "barbell",
    muscles: [
      { muscleGroup: "quads", role: "primary" },
      { muscleGroup: "calves", role: "secondary" },
      { muscleGroup: "glutes", role: "secondary" },
      { muscleGroup: "hamstrings", role: "secondary" },
    ],
  },
  {
    name: "Lunges",
    movementPattern: "lunge",
    equipment: "dumbbell",
    muscles: [
      { muscleGroup: "quads", role: "primary" },
      { muscleGroup: "calves", role: "secondary" },
      { muscleGroup: "glutes", role: "secondary" },
      { muscleGroup: "hamstrings", role: "secondary" },
    ],
  },
  {
    name: "Lying Leg Curls",
    movementPattern: "pull",
    equipment: "machine",
    muscles: [{ muscleGroup: "hamstrings", role: "primary" }],
  },
  {
    name: "Lying Pronation",
    movementPattern: "pull",
    equipment: "dumbbell",
    muscles: [{ muscleGroup: "forearms", role: "primary" }],
  },
  {
    name: "Lying T-Bar Row",
    movementPattern: "pull",
    equipment: "machine",
    muscles: [
      { muscleGroup: "back", role: "primary" },
      { muscleGroup: "biceps", role: "secondary" },
    ],
  },
  {
    name: "Lying Tricep Extension",
    movementPattern: "push",
    equipment: "dumbbell",
    muscles: [
      { muscleGroup: "triceps", role: "primary" },
      { muscleGroup: "chest", role: "secondary" },
      { muscleGroup: "delts", role: "secondary" },
    ],
  },
  {
    name: "Lying Triceps Extension",
    movementPattern: "push",
    equipment: "cable",
    muscles: [{ muscleGroup: "triceps", role: "primary" }],
  },
  {
    name: "Muscle Up",
    movementPattern: "pull",
    muscles: [
      { muscleGroup: "back", role: "primary" },
      { muscleGroup: "biceps", role: "secondary" },
      { muscleGroup: "core", role: "secondary" },
      { muscleGroup: "delts", role: "secondary" },
      { muscleGroup: "forearms", role: "secondary" },
      { muscleGroup: "traps", role: "secondary" },
      { muscleGroup: "triceps", role: "secondary" },
    ],
  },
  {
    name: "One-Arm Long Bar Row",
    movementPattern: "pull",
    equipment: "barbell",
    muscles: [
      { muscleGroup: "back", role: "primary" },
      { muscleGroup: "biceps", role: "secondary" },
    ],
  },
  {
    name: "One-Arm Row",
    movementPattern: "pull",
    equipment: "kettlebell",
    muscles: [
      { muscleGroup: "back", role: "primary" },
      { muscleGroup: "biceps", role: "secondary" },
    ],
  },
  {
    name: "One-Arm Split Jerk",
    movementPattern: "push",
    equipment: "kettlebell",
    muscles: [
      { muscleGroup: "delts", role: "primary" },
      { muscleGroup: "glutes", role: "secondary" },
      { muscleGroup: "hamstrings", role: "secondary" },
      { muscleGroup: "quads", role: "secondary" },
      { muscleGroup: "triceps", role: "secondary" },
    ],
  },
  {
    name: "One-Arm Split Snatch",
    movementPattern: "pull",
    equipment: "kettlebell",
    muscles: [
      { muscleGroup: "delts", role: "primary" },
      { muscleGroup: "hamstrings", role: "secondary" },
      { muscleGroup: "quads", role: "secondary" },
    ],
  },
  {
    name: "One-Arm Swings",
    movementPattern: "hinge",
    equipment: "kettlebell",
    muscles: [
      { muscleGroup: "hamstrings", role: "primary" },
      { muscleGroup: "back", role: "secondary" },
      { muscleGroup: "calves", role: "secondary" },
      { muscleGroup: "delts", role: "secondary" },
      { muscleGroup: "glutes", role: "secondary" },
    ],
  },
  {
    name: "One-Legged Deadlift",
    movementPattern: "hinge",
    equipment: "kettlebell",
    muscles: [
      { muscleGroup: "hamstrings", role: "primary" },
      { muscleGroup: "back", role: "secondary" },
      { muscleGroup: "glutes", role: "secondary" },
    ],
  },
  {
    name: "One-Legged Kickback",
    movementPattern: "push",
    equipment: "cable",
    muscles: [
      { muscleGroup: "glutes", role: "primary" },
      { muscleGroup: "hamstrings", role: "secondary" },
    ],
  },
  {
    name: "Pallof Press",
    movementPattern: "core",
    equipment: "cable",
    muscles: [
      { muscleGroup: "core", role: "primary" },
      { muscleGroup: "chest", role: "secondary" },
      { muscleGroup: "delts", role: "secondary" },
      { muscleGroup: "triceps", role: "secondary" },
    ],
  },
  {
    name: "Pallof Press With Rotation",
    movementPattern: "core",
    equipment: "cable",
    muscles: [
      { muscleGroup: "core", role: "primary" },
      { muscleGroup: "chest", role: "secondary" },
      { muscleGroup: "delts", role: "secondary" },
      { muscleGroup: "triceps", role: "secondary" },
    ],
  },
  {
    name: "Physioball Hip Bridge",
    movementPattern: "push",
    equipment: "exercise-ball",
    muscles: [
      { muscleGroup: "glutes", role: "primary" },
      { muscleGroup: "hamstrings", role: "secondary" },
    ],
  },
  {
    name: "Pistol Squat",
    movementPattern: "squat",
    equipment: "kettlebell",
    muscles: [
      { muscleGroup: "quads", role: "primary" },
      { muscleGroup: "calves", role: "secondary" },
      { muscleGroup: "delts", role: "secondary" },
      { muscleGroup: "glutes", role: "secondary" },
      { muscleGroup: "hamstrings", role: "secondary" },
    ],
  },
  {
    name: "Plank",
    movementPattern: "core",
    equipment: "bodyweight",
    muscles: [{ muscleGroup: "core", role: "primary" }],
  },
  {
    name: "Plyo Pushups",
    movementPattern: "push",
    equipment: "kettlebell",
    muscles: [
      { muscleGroup: "chest", role: "primary" },
      { muscleGroup: "delts", role: "secondary" },
      { muscleGroup: "triceps", role: "secondary" },
    ],
  },
  {
    name: "Power Clean",
    movementPattern: "pull",
    equipment: "barbell",
    muscles: [
      { muscleGroup: "hamstrings", role: "primary" },
      { muscleGroup: "back", role: "secondary" },
      { muscleGroup: "calves", role: "secondary" },
      { muscleGroup: "delts", role: "secondary" },
      { muscleGroup: "forearms", role: "secondary" },
      { muscleGroup: "glutes", role: "secondary" },
      { muscleGroup: "quads", role: "secondary" },
      { muscleGroup: "traps", role: "secondary" },
      { muscleGroup: "triceps", role: "secondary" },
    ],
  },
  {
    name: "Power Jerk",
    movementPattern: "push",
    equipment: "barbell",
    muscles: [
      { muscleGroup: "quads", role: "primary" },
      { muscleGroup: "calves", role: "secondary" },
      { muscleGroup: "core", role: "secondary" },
      { muscleGroup: "delts", role: "secondary" },
      { muscleGroup: "glutes", role: "secondary" },
      { muscleGroup: "hamstrings", role: "secondary" },
      { muscleGroup: "triceps", role: "secondary" },
    ],
  },
  {
    name: "Power Snatch",
    movementPattern: "pull",
    equipment: "barbell",
    muscles: [
      { muscleGroup: "hamstrings", role: "primary" },
      { muscleGroup: "back", role: "secondary" },
      { muscleGroup: "calves", role: "secondary" },
      { muscleGroup: "delts", role: "secondary" },
      { muscleGroup: "glutes", role: "secondary" },
      { muscleGroup: "quads", role: "secondary" },
      { muscleGroup: "traps", role: "secondary" },
      { muscleGroup: "triceps", role: "secondary" },
    ],
  },
  {
    name: "Preacher Curl",
    movementPattern: "pull",
    equipment: "barbell",
    muscles: [
      { muscleGroup: "biceps", role: "primary" },
      { muscleGroup: "forearms", role: "secondary" },
    ],
  },
  {
    name: "Preacher Curls",
    movementPattern: "pull",
    equipment: "machine",
    muscles: [{ muscleGroup: "biceps", role: "primary" }],
  },
  {
    name: "Press Sit-Up",
    movementPattern: "core",
    equipment: "barbell",
    muscles: [
      { muscleGroup: "core", role: "primary" },
      { muscleGroup: "chest", role: "secondary" },
      { muscleGroup: "delts", role: "secondary" },
      { muscleGroup: "triceps", role: "secondary" },
    ],
  },
  {
    name: "Pull Apart",
    movementPattern: "pull",
    equipment: "band",
    muscles: [
      { muscleGroup: "delts", role: "primary" },
      { muscleGroup: "back", role: "secondary" },
      { muscleGroup: "traps", role: "secondary" },
    ],
  },
  {
    name: "Pull Through",
    movementPattern: "pull",
    equipment: "cable",
    muscles: [
      { muscleGroup: "glutes", role: "primary" },
      { muscleGroup: "back", role: "secondary" },
      { muscleGroup: "hamstrings", role: "secondary" },
    ],
  },
  {
    name: "Pull-In",
    movementPattern: "core",
    equipment: "exercise-ball",
    muscles: [{ muscleGroup: "core", role: "primary" }],
  },
  {
    name: "Pullups",
    movementPattern: "pull",
    equipment: "bodyweight",
    muscles: [
      { muscleGroup: "back", role: "primary" },
      { muscleGroup: "biceps", role: "secondary" },
    ],
  },
  {
    name: "Push-Ups (Feet Elevated)",
    movementPattern: "push",
    equipment: "exercise-ball",
    muscles: [
      { muscleGroup: "chest", role: "primary" },
      { muscleGroup: "delts", role: "secondary" },
      { muscleGroup: "triceps", role: "secondary" },
    ],
  },
  {
    name: "Pushups",
    movementPattern: "push",
    equipment: "bodyweight",
    muscles: [
      { muscleGroup: "chest", role: "primary" },
      { muscleGroup: "delts", role: "secondary" },
      { muscleGroup: "triceps", role: "secondary" },
    ],
  },
  {
    name: "Rack Pulls",
    movementPattern: "pull",
    equipment: "barbell",
    muscles: [
      { muscleGroup: "back", role: "primary" },
      { muscleGroup: "forearms", role: "secondary" },
      { muscleGroup: "glutes", role: "secondary" },
      { muscleGroup: "hamstrings", role: "secondary" },
      { muscleGroup: "traps", role: "secondary" },
    ],
  },
  {
    name: "Raise",
    movementPattern: "pull",
    equipment: "dumbbell",
    muscles: [
      { muscleGroup: "delts", role: "primary" },
      { muscleGroup: "biceps", role: "secondary" },
    ],
  },
  {
    name: "Rear Delt Fly",
    movementPattern: "pull",
    equipment: "cable",
    muscles: [{ muscleGroup: "delts", role: "primary" }],
  },
  {
    name: "Rear Delt Row",
    movementPattern: "pull",
    equipment: "barbell",
    muscles: [
      { muscleGroup: "delts", role: "primary" },
      { muscleGroup: "back", role: "secondary" },
      { muscleGroup: "biceps", role: "secondary" },
    ],
  },
  {
    name: "Reverse Crunch",
    movementPattern: "core",
    equipment: "bodyweight",
    muscles: [{ muscleGroup: "core", role: "primary" }],
  },
  {
    name: "Reverse Curl",
    movementPattern: "pull",
    equipment: "cable",
    muscles: [
      { muscleGroup: "biceps", role: "primary" },
      { muscleGroup: "forearms", role: "secondary" },
    ],
  },
  {
    name: "Reverse Flyes",
    movementPattern: "pull",
    equipment: "dumbbell",
    muscles: [{ muscleGroup: "delts", role: "primary" }],
  },
  {
    name: "Reverse Hyperextension",
    movementPattern: "hinge",
    equipment: "machine",
    muscles: [
      { muscleGroup: "hamstrings", role: "primary" },
      { muscleGroup: "calves", role: "secondary" },
      { muscleGroup: "glutes", role: "secondary" },
    ],
  },
  {
    name: "Reverse Preacher Curls",
    movementPattern: "pull",
    equipment: "ez-bar",
    muscles: [
      { muscleGroup: "biceps", role: "primary" },
      { muscleGroup: "forearms", role: "secondary" },
    ],
  },
  {
    name: "Ring Dips",
    movementPattern: "push",
    muscles: [
      { muscleGroup: "triceps", role: "primary" },
      { muscleGroup: "chest", role: "secondary" },
      { muscleGroup: "delts", role: "secondary" },
    ],
  },
  {
    name: "Romanian Deadlift",
    movementPattern: "hinge",
    equipment: "barbell",
    muscles: [
      { muscleGroup: "hamstrings", role: "primary" },
      { muscleGroup: "back", role: "secondary" },
      { muscleGroup: "calves", role: "secondary" },
      { muscleGroup: "glutes", role: "secondary" },
    ],
  },
  {
    name: "Rope Crunch",
    movementPattern: "core",
    equipment: "cable",
    muscles: [{ muscleGroup: "core", role: "primary" }],
  },
  {
    name: "Rope Overhead Triceps Extension",
    movementPattern: "push",
    equipment: "cable",
    muscles: [{ muscleGroup: "triceps", role: "primary" }],
  },
  {
    name: "Rope Rear-Delt Rows",
    movementPattern: "pull",
    equipment: "cable",
    muscles: [
      { muscleGroup: "delts", role: "primary" },
      { muscleGroup: "back", role: "secondary" },
      { muscleGroup: "biceps", role: "secondary" },
    ],
  },
  {
    name: "Russian Twist",
    movementPattern: "core",
    equipment: "bodyweight",
    muscles: [
      { muscleGroup: "core", role: "primary" },
      { muscleGroup: "back", role: "secondary" },
    ],
  },
  {
    name: "Russian Twists",
    movementPattern: "core",
    equipment: "cable",
    muscles: [{ muscleGroup: "core", role: "primary" }],
  },
  {
    name: "Seated Calf Raise",
    movementPattern: "push",
    equipment: "barbell",
    muscles: [{ muscleGroup: "calves", role: "primary" }],
  },
  {
    name: "Seated Hamstring Curl",
    movementPattern: "pull",
    equipment: "band",
    muscles: [{ muscleGroup: "hamstrings", role: "primary" }],
  },
  {
    name: "Seated Lateral Raise",
    movementPattern: "pull",
    equipment: "cable",
    muscles: [
      { muscleGroup: "delts", role: "primary" },
      { muscleGroup: "back", role: "secondary" },
      { muscleGroup: "traps", role: "secondary" },
    ],
  },
  {
    name: "Seated Leg Tucks",
    movementPattern: "core",
    equipment: "bodyweight",
    muscles: [{ muscleGroup: "core", role: "primary" }],
  },
  {
    name: "Seated Palm-Up Wrist Curl",
    movementPattern: "pull",
    equipment: "barbell",
    muscles: [{ muscleGroup: "forearms", role: "primary" }],
  },
  {
    name: "Seated Palms-Up Wrist Curl",
    movementPattern: "pull",
    equipment: "dumbbell",
    muscles: [{ muscleGroup: "forearms", role: "primary" }],
  },
  {
    name: "Seated Rows",
    movementPattern: "pull",
    equipment: "cable",
    muscles: [
      { muscleGroup: "back", role: "primary" },
      { muscleGroup: "biceps", role: "secondary" },
      { muscleGroup: "delts", role: "secondary" },
    ],
  },
  {
    name: "Shoulder Press",
    movementPattern: "push",
    equipment: "barbell",
    muscles: [
      { muscleGroup: "delts", role: "primary" },
      { muscleGroup: "chest", role: "secondary" },
      { muscleGroup: "triceps", role: "secondary" },
    ],
  },
  {
    name: "Shrug",
    movementPattern: "pull",
    equipment: "barbell",
    muscles: [
      { muscleGroup: "traps", role: "primary" },
      { muscleGroup: "forearms", role: "secondary" },
    ],
  },
  {
    name: "Shrugs",
    movementPattern: "pull",
    equipment: "cable",
    muscles: [{ muscleGroup: "traps", role: "primary" }],
  },
  {
    name: "Side Bend",
    movementPattern: "core",
    equipment: "barbell",
    muscles: [
      { muscleGroup: "core", role: "primary" },
      { muscleGroup: "back", role: "secondary" },
    ],
  },
  {
    name: "Side Split Squat",
    movementPattern: "squat",
    equipment: "barbell",
    muscles: [
      { muscleGroup: "quads", role: "primary" },
      { muscleGroup: "back", role: "secondary" },
      { muscleGroup: "calves", role: "secondary" },
      { muscleGroup: "hamstrings", role: "secondary" },
    ],
  },
  {
    name: "Single Leg Push-off",
    movementPattern: "push",
    muscles: [
      { muscleGroup: "quads", role: "primary" },
      { muscleGroup: "calves", role: "secondary" },
      { muscleGroup: "hamstrings", role: "secondary" },
    ],
  },
  {
    name: "Sit-Up",
    movementPattern: "core",
    equipment: "bodyweight",
    muscles: [{ muscleGroup: "core", role: "primary" }],
  },
  {
    name: "Skull Crusher",
    movementPattern: "push",
    equipment: "band",
    muscles: [{ muscleGroup: "triceps", role: "primary" }],
  },
  {
    name: "Skullcrusher",
    movementPattern: "push",
    equipment: "ez-bar",
    muscles: [
      { muscleGroup: "triceps", role: "primary" },
      { muscleGroup: "forearms", role: "secondary" },
    ],
  },
  {
    name: "Smith Single-Leg Split Squat",
    movementPattern: "squat",
    equipment: "machine",
    muscles: [
      { muscleGroup: "quads", role: "primary" },
      { muscleGroup: "calves", role: "secondary" },
      { muscleGroup: "glutes", role: "secondary" },
      { muscleGroup: "hamstrings", role: "secondary" },
    ],
  },
  {
    name: "Snatch",
    movementPattern: "pull",
    equipment: "barbell",
    muscles: [
      { muscleGroup: "quads", role: "primary" },
      { muscleGroup: "back", role: "secondary" },
      { muscleGroup: "biceps", role: "secondary" },
      { muscleGroup: "delts", role: "secondary" },
      { muscleGroup: "glutes", role: "secondary" },
      { muscleGroup: "hamstrings", role: "secondary" },
      { muscleGroup: "traps", role: "secondary" },
      { muscleGroup: "triceps", role: "secondary" },
    ],
  },
  {
    name: "Spider Curl",
    movementPattern: "pull",
    equipment: "ez-bar",
    muscles: [{ muscleGroup: "biceps", role: "primary" }],
  },
  {
    name: "Split Clean",
    movementPattern: "pull",
    equipment: "barbell",
    muscles: [
      { muscleGroup: "quads", role: "primary" },
      { muscleGroup: "back", role: "secondary" },
      { muscleGroup: "calves", role: "secondary" },
      { muscleGroup: "delts", role: "secondary" },
      { muscleGroup: "forearms", role: "secondary" },
      { muscleGroup: "glutes", role: "secondary" },
      { muscleGroup: "hamstrings", role: "secondary" },
      { muscleGroup: "traps", role: "secondary" },
    ],
  },
  {
    name: "Split Jerk",
    movementPattern: "push",
    equipment: "barbell",
    muscles: [
      { muscleGroup: "quads", role: "primary" },
      { muscleGroup: "delts", role: "secondary" },
      { muscleGroup: "glutes", role: "secondary" },
      { muscleGroup: "hamstrings", role: "secondary" },
      { muscleGroup: "triceps", role: "secondary" },
    ],
  },
  {
    name: "Split Snatch",
    movementPattern: "pull",
    equipment: "barbell",
    muscles: [
      { muscleGroup: "hamstrings", role: "primary" },
      { muscleGroup: "back", role: "secondary" },
      { muscleGroup: "calves", role: "secondary" },
      { muscleGroup: "delts", role: "secondary" },
      { muscleGroup: "forearms", role: "secondary" },
      { muscleGroup: "glutes", role: "secondary" },
      { muscleGroup: "quads", role: "secondary" },
      { muscleGroup: "traps", role: "secondary" },
      { muscleGroup: "triceps", role: "secondary" },
    ],
  },
  {
    name: "Split Squat",
    movementPattern: "squat",
    equipment: "dumbbell",
    muscles: [
      { muscleGroup: "quads", role: "primary" },
      { muscleGroup: "glutes", role: "secondary" },
      { muscleGroup: "hamstrings", role: "secondary" },
    ],
  },
  {
    name: "Squat",
    movementPattern: "squat",
    equipment: "bodyweight",
    muscles: [
      { muscleGroup: "quads", role: "primary" },
      { muscleGroup: "back", role: "secondary" },
      { muscleGroup: "calves", role: "secondary" },
      { muscleGroup: "glutes", role: "secondary" },
      { muscleGroup: "hamstrings", role: "secondary" },
    ],
  },
  {
    name: "Standing Low-Pulley One-Arm Triceps Extension",
    movementPattern: "push",
    equipment: "cable",
    muscles: [
      { muscleGroup: "triceps", role: "primary" },
      { muscleGroup: "chest", role: "secondary" },
      { muscleGroup: "delts", role: "secondary" },
    ],
  },
  {
    name: "Standing Overhead Triceps Extension",
    movementPattern: "push",
    equipment: "barbell",
    muscles: [
      { muscleGroup: "triceps", role: "primary" },
      { muscleGroup: "delts", role: "secondary" },
    ],
  },
  {
    name: "Standing Towel Triceps Extension",
    movementPattern: "push",
    equipment: "bodyweight",
    muscles: [{ muscleGroup: "triceps", role: "primary" }],
  },
  {
    name: "Standing Upright Row",
    movementPattern: "pull",
    equipment: "dumbbell",
    muscles: [
      { muscleGroup: "traps", role: "primary" },
      { muscleGroup: "biceps", role: "secondary" },
      { muscleGroup: "delts", role: "secondary" },
    ],
  },
  {
    name: "Stiff-Legged Deadlift",
    movementPattern: "hinge",
    equipment: "dumbbell",
    muscles: [
      { muscleGroup: "hamstrings", role: "primary" },
      { muscleGroup: "back", role: "secondary" },
      { muscleGroup: "glutes", role: "secondary" },
    ],
  },
  {
    name: "Straight-Arm Pulldown",
    movementPattern: "pull",
    equipment: "cable",
    muscles: [{ muscleGroup: "back", role: "primary" }],
  },
  {
    name: "Suspended Split Squat",
    movementPattern: "squat",
    muscles: [
      { muscleGroup: "quads", role: "primary" },
      { muscleGroup: "calves", role: "secondary" },
      { muscleGroup: "glutes", role: "secondary" },
      { muscleGroup: "hamstrings", role: "secondary" },
    ],
  },
  {
    name: "Thigh Abductor",
    movementPattern: "push",
    equipment: "machine",
    muscles: [{ muscleGroup: "glutes", role: "primary" }],
  },
  {
    name: "Thruster",
    movementPattern: "push",
    equipment: "kettlebell",
    muscles: [
      { muscleGroup: "delts", role: "primary" },
      { muscleGroup: "quads", role: "secondary" },
      { muscleGroup: "triceps", role: "secondary" },
    ],
  },
  {
    name: "Tricep Kickback",
    movementPattern: "push",
    equipment: "dumbbell",
    muscles: [{ muscleGroup: "triceps", role: "primary" }],
  },
  {
    name: "Triceps Extension",
    movementPattern: "push",
    equipment: "machine",
    muscles: [{ muscleGroup: "triceps", role: "primary" }],
  },
  {
    name: "Triceps Pushdown",
    movementPattern: "push",
    equipment: "cable",
    muscles: [{ muscleGroup: "triceps", role: "primary" }],
  },
  {
    name: "Turkish Get-Up (Lunge style)",
    movementPattern: "lunge",
    equipment: "kettlebell",
    muscles: [
      { muscleGroup: "delts", role: "primary" },
      { muscleGroup: "core", role: "secondary" },
      { muscleGroup: "hamstrings", role: "secondary" },
      { muscleGroup: "quads", role: "secondary" },
      { muscleGroup: "triceps", role: "secondary" },
    ],
  },
  {
    name: "Turkish Get-Up (Squat style)",
    movementPattern: "squat",
    equipment: "kettlebell",
    muscles: [
      { muscleGroup: "delts", role: "primary" },
      { muscleGroup: "calves", role: "secondary" },
      { muscleGroup: "core", role: "secondary" },
      { muscleGroup: "hamstrings", role: "secondary" },
      { muscleGroup: "quads", role: "secondary" },
      { muscleGroup: "triceps", role: "secondary" },
    ],
  },
  {
    name: "Upright Row",
    movementPattern: "pull",
    equipment: "barbell",
    muscles: [
      { muscleGroup: "delts", role: "primary" },
      { muscleGroup: "traps", role: "primary" },
      { muscleGroup: "back", role: "secondary" },
      { muscleGroup: "biceps", role: "secondary" },
    ],
  },
  {
    name: "Walking Lunge",
    movementPattern: "lunge",
    equipment: "bodyweight",
    muscles: [
      { muscleGroup: "quads", role: "primary" },
      { muscleGroup: "calves", role: "secondary" },
      { muscleGroup: "glutes", role: "secondary" },
      { muscleGroup: "hamstrings", role: "secondary" },
    ],
  },
  {
    name: "Weighted Crunches",
    movementPattern: "core",
    equipment: "medicine-ball",
    muscles: [{ muscleGroup: "core", role: "primary" }],
  },
  {
    name: "Weighted Hyperextension",
    movementPattern: "hinge",
    equipment: "exercise-ball",
    muscles: [
      { muscleGroup: "back", role: "primary" },
      { muscleGroup: "glutes", role: "secondary" },
      { muscleGroup: "hamstrings", role: "secondary" },
    ],
  },
  {
    name: "Weighted Side Bend",
    movementPattern: "core",
    equipment: "exercise-ball",
    muscles: [{ muscleGroup: "core", role: "primary" }],
  },
  {
    name: "Wrist Curl",
    movementPattern: "pull",
    equipment: "cable",
    muscles: [{ muscleGroup: "forearms", role: "primary" }],
  },
  {
    name: "Wrist Roller",
    movementPattern: "pull",
    muscles: [
      { muscleGroup: "forearms", role: "primary" },
      { muscleGroup: "delts", role: "secondary" },
    ],
  },
  {
    name: "Zottman Preacher Curl",
    movementPattern: "pull",
    equipment: "dumbbell",
    muscles: [
      { muscleGroup: "biceps", role: "primary" },
      { muscleGroup: "forearms", role: "secondary" },
    ],
  },
];
